# Generated by Django 6.0.2 on 2026-03-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_optimize_task_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_user_id_c0fce1_idx',
            old_name='tasks_task_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_user_id_9ed24b_idx',
            old_name='tasks_task_user_deadline_idx',
        ),
    ]
