# Generated by Django 6.0.2 on 2026-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_discription_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accumulated_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='is_hard_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
